import type { GameFormat } from '../types/game'
import type { Formation } from '../types/formation'

export const FORMATIONS: Formation[] = [
  {
    key: '7v7-2-3-1',
    name: '2-3-1',
    format: '7v7',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 25, y: 75 },
      { id: 'd2', label: 'DEF', x: 75, y: 75 },
      { id: 'm1', label: 'MID', x: 20, y: 50 },
      { id: 'm2', label: 'MID', x: 50, y: 50 },
      { id: 'm3', label: 'MID', x: 80, y: 50 },
      { id: 'f1', label: 'FWD', x: 50, y: 20 },
    ],
  },
  {
    key: '7v7-3-2-1',
    name: '3-2-1',
    format: '7v7',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 20, y: 75 },
      { id: 'd2', label: 'DEF', x: 50, y: 78 },
      { id: 'd3', label: 'DEF', x: 80, y: 75 },
      { id: 'm1', label: 'MID', x: 35, y: 50 },
      { id: 'm2', label: 'MID', x: 65, y: 50 },
      { id: 'f1', label: 'FWD', x: 50, y: 20 },
    ],
  },
  {
    key: '7v7-3-1-2',
    name: '3-1-2',
    format: '7v7',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 20, y: 75 },
      { id: 'd2', label: 'DEF', x: 50, y: 78 },
      { id: 'd3', label: 'DEF', x: 80, y: 75 },
      { id: 'm1', label: 'MID', x: 50, y: 50 },
      { id: 'f1', label: 'FWD', x: 35, y: 20 },
      { id: 'f2', label: 'FWD', x: 65, y: 20 },
    ],
  },
  {
    key: '9v9-3-3-2',
    name: '3-3-2',
    format: '9v9',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 20, y: 75 },
      { id: 'd2', label: 'DEF', x: 50, y: 78 },
      { id: 'd3', label: 'DEF', x: 80, y: 75 },
      { id: 'm1', label: 'MID', x: 20, y: 50 },
      { id: 'm2', label: 'MID', x: 50, y: 53 },
      { id: 'm3', label: 'MID', x: 80, y: 50 },
      { id: 'f1', label: 'FWD', x: 35, y: 20 },
      { id: 'f2', label: 'FWD', x: 65, y: 20 },
    ],
  },
  {
    key: '9v9-3-2-3',
    name: '3-2-3',
    format: '9v9',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 20, y: 75 },
      { id: 'd2', label: 'DEF', x: 50, y: 78 },
      { id: 'd3', label: 'DEF', x: 80, y: 75 },
      { id: 'm1', label: 'MID', x: 35, y: 52 },
      { id: 'm2', label: 'MID', x: 65, y: 52 },
      { id: 'f1', label: 'FWD', x: 20, y: 20 },
      { id: 'f2', label: 'FWD', x: 50, y: 15 },
      { id: 'f3', label: 'FWD', x: 80, y: 20 },
    ],
  },
  {
    key: '9v9-4-3-1',
    name: '4-3-1',
    format: '9v9',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 15, y: 78 },
      { id: 'd2', label: 'DEF', x: 38, y: 80 },
      { id: 'd3', label: 'DEF', x: 62, y: 80 },
      { id: 'd4', label: 'DEF', x: 85, y: 78 },
      { id: 'm1', label: 'MID', x: 20, y: 50 },
      { id: 'm2', label: 'MID', x: 50, y: 53 },
      { id: 'm3', label: 'MID', x: 80, y: 50 },
      { id: 'f1', label: 'FWD', x: 50, y: 20 },
    ],
  },
  {
    key: '11v11-4-4-2',
    name: '4-4-2',
    format: '11v11',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 15, y: 78 },
      { id: 'd2', label: 'DEF', x: 38, y: 80 },
      { id: 'd3', label: 'DEF', x: 62, y: 80 },
      { id: 'd4', label: 'DEF', x: 85, y: 78 },
      { id: 'm1', label: 'MID', x: 15, y: 50 },
      { id: 'm2', label: 'MID', x: 38, y: 53 },
      { id: 'm3', label: 'MID', x: 62, y: 53 },
      { id: 'm4', label: 'MID', x: 85, y: 50 },
      { id: 'f1', label: 'FWD', x: 35, y: 20 },
      { id: 'f2', label: 'FWD', x: 65, y: 20 },
    ],
  },
  {
    key: '11v11-4-3-3',
    name: '4-3-3',
    format: '11v11',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 15, y: 78 },
      { id: 'd2', label: 'DEF', x: 38, y: 80 },
      { id: 'd3', label: 'DEF', x: 62, y: 80 },
      { id: 'd4', label: 'DEF', x: 85, y: 78 },
      { id: 'm1', label: 'MID', x: 25, y: 52 },
      { id: 'm2', label: 'MID', x: 50, y: 55 },
      { id: 'm3', label: 'MID', x: 75, y: 52 },
      { id: 'f1', label: 'FWD', x: 20, y: 20 },
      { id: 'f2', label: 'FWD', x: 50, y: 15 },
      { id: 'f3', label: 'FWD', x: 80, y: 20 },
    ],
  },
  {
    key: '11v11-4-2-3-1',
    name: '4-2-3-1',
    format: '11v11',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 15, y: 78 },
      { id: 'd2', label: 'DEF', x: 38, y: 80 },
      { id: 'd3', label: 'DEF', x: 62, y: 80 },
      { id: 'd4', label: 'DEF', x: 85, y: 78 },
      { id: 'dm1', label: 'MID', x: 35, y: 62 },
      { id: 'dm2', label: 'MID', x: 65, y: 62 },
      { id: 'am1', label: 'MID', x: 20, y: 40 },
      { id: 'am2', label: 'MID', x: 50, y: 42 },
      { id: 'am3', label: 'MID', x: 80, y: 40 },
      { id: 'f1', label: 'FWD', x: 50, y: 18 },
    ],
  },
  {
    key: '11v11-3-5-2',
    name: '3-5-2',
    format: '11v11',
    slots: [
      { id: 'gk', label: 'GK', x: 50, y: 95 },
      { id: 'd1', label: 'DEF', x: 25, y: 78 },
      { id: 'd2', label: 'DEF', x: 50, y: 80 },
      { id: 'd3', label: 'DEF', x: 75, y: 78 },
      { id: 'm1', label: 'MID', x: 10, y: 55 },
      { id: 'm2', label: 'MID', x: 32, y: 50 },
      { id: 'm3', label: 'MID', x: 50, y: 53 },
      { id: 'm4', label: 'MID', x: 68, y: 50 },
      { id: 'm5', label: 'MID', x: 90, y: 55 },
      { id: 'f1', label: 'FWD', x: 35, y: 20 },
      { id: 'f2', label: 'FWD', x: 65, y: 20 },
    ],
  },
]

export function getFormationsForFormat(format: GameFormat): Formation[] {
  return FORMATIONS.filter((f) => f.format === format)
}

export function getFormation(key: string): Formation | undefined {
  return FORMATIONS.find((f) => f.key === key)
}
